### ISSUE TITLE
`load("@xchammer//:BazelExtensions/xcodeproject.bzl", "xcode_project")` instead of `load("@xchammer//:xcodeproject.bzl", "xcode_project")`?

### ISSUE THREAD

**Issue by imWildCat** [bazel-xcode/xchammer#297]
In <https://github.com/pinterest/xchammer/blob/master/README.md>, it shows

`load("@xchammer//:xcodeproject.bzl", "xcode_project")`

I believe in the latest version, it is changed to `load("@xchammer//:BazelExtensions/xcodeproject.bzl", "xcode_project")`.

I'm new to Bazel. Should we update README?

**Comment by thiagohmcruz** [comment]
Resolved here: https://github.com/bazel-xcode/xchammer/pull/292
